[package]
name = "lyst"
version = "0.1.0"
authors = ["tharvik <tharvik@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = [
  "fs",
  "io-util",
  "macros",
  "rt-multi-thread",
  "rt",
  "tracing", # debug
] }
tokio-stream = "0.1"
async-stream = "0.3"
tracing = "0.1"
console-subscriber = "0.1"
pin-project = "1"
owning_ref = "0.4"
