on: [push, pull_request]

name: lint, build, test

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: git checkout

      - uses: actions-rs/toolchain@v1
        name: install toolchain
        with:
          profile: minimal
          toolchain: stable

      - run: sudo apt install libsdl2-dev libsdl2-{image,mixer}-dev

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: cargo check
        with:
          command: check

      - uses: actions-rs/cargo@v1
        name: cargo clippy
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: sudo apt install libsdl2-dev libsdl2-{image,mixer}-dev

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --all-features

  deny:
    name: cargo deny
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: git checkout

      - uses: actions-rs/toolchain@v1
        name: install toolchain
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: install cargo deny
        with:
          command: install
          args: cargo-deny

      - uses: actions-rs/cargo@v1
        name: cargo deny
        with:
          command: deny
          args: check
