on: [push, pull_request]

name: lint, build, test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - run: sudo apt install libsdl2-dev libsdl2-{image,mixer}-dev

      - uses: swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: --check

      - uses: actions-rs/cargo@v1
        name: cargo check
        with:
          command: check

      - uses: actions-rs/cargo@v1
        name: cargo clippy
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - run: sudo apt install libsdl2-dev libsdl2-{image,mixer}-dev

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --all-features

  list-fuzz-targets:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      fuzz-targets: ${{ steps.list.outputs.targets }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: install cargo fuzz
        with:
          command: install
          args: cargo-fuzz

      - id: list
        name: cargo fuzz list
        run: |
          targets_json=$(cargo fuzz list | xargs | sed 's/ /","/g')
          echo "targets=[\"$targets_json\"]" >> "$GITHUB_OUTPUT"
        working-directory: packbits

  fuzz:
    runs-on: ubuntu-latest
    needs: [list-fuzz-targets]
    strategy:
      matrix:
        target: ${{ fromJSON(needs.list-fuzz-targets.outputs.fuzz-targets) }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true

      - run: sudo apt install libsdl2-dev libsdl2-{image,mixer}-dev

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: install cargo fuzz
        with:
          command: install
          args: cargo-fuzz

      - uses: actions/cache@v3
        with:
          path: packbits/fuzz/corpus
          key: ${{ matrix.target }}-packbits-corpus

      - run: cargo fuzz run ${{ matrix.target }} -- -max_total_time=60
        working-directory: packbits

  deny:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/cargo@v1
        name: install cargo deny
        with:
          command: install
          args: cargo-deny

      - uses: actions-rs/cargo@v1
        name: cargo deny
        with:
          command: deny
          args: check
